services:
  dazhbog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dazhbog
    ports:
      - "1235:1235"
      - "8080:8080"
    volumes:
      - ./config.toml:/app/config.toml
      - ./data:/app/data
    restart: unless-stopped
